### ISSUE TITLE
Once again, make user input more friendly

### ISSUE THREAD

**Issue by jhulen** [QT-Pies/inventory-project#103]
As a developer, I would like our program to be easy for the user to use. Having to re-enter choices because of case-sensitivity is frustrating, and having to type long option names is inconvenient and easy to mess up. 
I will make user input more simple by making simple choices for user input, most likely via number system, such as select 1 for print, 2 for add, etc.

**Comment by nshoap-utk** [comment]
I don't know if the group wants this, but do it if you want.
