### ISSUE TITLE
Storage Room Visual

### ISSUE THREAD

**Issue by vbroda17** [QT-Pies/inventory-project#11]
# Visualized Storage
I think that a future where the user can create a layout of there storage area or warehouse so they can see a visual of their inventory would be helpful.

## Acceptance Criteria
1. Add a way for users to create a basic layout
2. Add a way for users to Add where items are
3. Make sure it is easy to edit and clear to view

**Comment by nshoap-utk** [comment]
Are we still going to do this, or can we close this issue?
