### ISSUE TITLE
Rough draft of GUI

### ISSUE THREAD

**Issue by nshoap-utk** [QT-Pies/inventory-project#18]
# GUI Draft
As a developer, I would like to have a general idea what we are working towards when creating the user interface.

## Acceptance Criteria
1. Sketch, non-functional GUI is created to demo GUI and how it should look and function.

**Comment by vbroda17** [comment]
![Inventory_Manager_ITEMS_GUI](https://user-images.githubusercontent.com/101155730/194971608-3154a204-e81f-46b0-82d0-76a35fdd5036.jpg)
![IMG_6903 - Copy](https://user-images.githubusercontent.com/101155730/194972046-c44611c5-bb69-4ecb-8423-ed071d36e5af.JPG)

**Comment by vbroda17** [comment]
The left side of the screen has a list for the user to pick what item they want to look at, and once selected, all of the useful information stored about the item will be presented. The plus and minus buttons are for adding and deleting items and the edit button if for editing item information. I think that something like this will be easiest for users to use.

The color scheme and other smaller details I think can be changed based on what everyone thinks looks good.
