### ISSUE TITLE
InventoryGenerator Update

### ISSUE THREAD

**Issue by nshoap-utk** [QT-Pies/inventory-project#88]
# InventoryGenerator  Update
As a developer, I would like our tools to be as high quality as possible and generate realistic output.

## Acceptance Criteria
1. Meaningful item names
2. Dates can support up to 31 days if month has that many
3. Prices more accurately reflect average store
4. Prices are more realistically distributed, i.e, a place like Walmart has electronics that may go up to several thousand, but if you walk in and grab a random item, it's probably going to be relatively low value.
5. Sub-categories are generated.
6. Sub-categories correspond with Category -- i.e, sub-cat ```Drink``` goes with category ```Perishable```.
7. Possibly generate location.

## Note
Most of these will be taken care of by converting grocery data to inventory data.

**Comment by nshoap-utk** [comment]
Moving to sprint 4

**Comment by josephwehby** [comment]
completed in Grocery Data to Inventory Data
